config/routes.rb
Rails.application.routes.draw do
  # get 'weather/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "weather#index"
  get '/search' => 'weather#search'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
require 'net/http'

class WeatherController < ApplicationController
  APP_ID = Rails.application.credentials.weather_api_key
  COORDINATES_URL = "https://api.openweathermap.org/geo/1.0/zip".freeze
  WEATHER_URL = "https://api.openweathermap.org/data/2.5/weather".freeze

  def index
  end

  def search
    ##
    # send postal_code to geocoding API to get the necessary cooridates (latitude longitude)
    # to the weather api
    postal_code_response = find_coordinates_by_postal_code(params[:postal_code])

    if postal_code_response['cod'].present? && postal_code_response['cod'] != '200'
      flash[:alert] = postal_code_response['message']
      return render action: :index
    end
    
    if Rails.cache.fetch(params[:postal_code]).present?
      flash.now[:alert] = "Weather data retrieved from cache"
      @weather_response = Rails.cache.read(params[:postal_code])
    else
      @weather_response = Rails.cache.fetch(params[:postal_code], expires_in: 30.minutes) do
        get_weather(lat: postal_code_response["lat"], lon: postal_code_response["lon"])
      end
    end
  end

  private

    def api_request(url:, params: {})
      uri = URI(url)
      uri.query = URI.encode_www_form(params)
      response = Net::HTTP.get_response(uri)
      JSON.parse(response.body)
    end

    def find_coordinates_by_postal_code(postal_code)
      api_request(url: COORDINATES_URL, 
                  params: { zip: postal_code, appid: Rails.application.credentials.weather_api_key })
    end

    def get_weather(lat:, lon:)
      api_request(url: WEATHER_URL, params: { lat: lat, lon: lon, units: "imperial", appid: APP_ID })
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
  def weather_icon(icon)
    "http://openweathermap.org/img/wn/#{icon}@2x.png"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# BootStrap CDN %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Weather App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/weather/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <div class="col-lg-12 mt-5">
      <% if flash[:alert] %>
        <div class="alert alert-warning"><%= flash[:alert] %></div>
      <% end %>
      <div class="mx-auto mt-5" style="width: 400px">
        <%= form_with(url: search_path, method: 'get', local: true) do %>
          <div class="form-control">
            <%= label_tag :postal_code, 'Enter postal code to retrieve the weather '%>
            <%= text_field_tag :postal_code, nil, placeholder: 'Eg. 90210', class: 'form-control' %>
            
            <%= button_tag 'Search', class: 'mt-2 btn btn-success btn-block' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/weather/search.html.erb
<div class="d-flex align-items-center justify-content-center">
  <div class="row mt-5">
    <% if flash[:alert] %>
        <div class="alert alert-warning"><%= flash[:alert] %></div>
      <% end %>
    <div class="col-lg-6">
      <dl>
        <dt>City</dt>
        <dd><%= @weather_response["name"] %></dd>
      </dl>
    </div>

    <div class="col-lg-6">
      <h4>Weather Info</h4>

      <dl>
        <% @weather_response["weather"].each do |weather| %>
          <dt><img src="<%= weather_icon(weather['icon']) %>"></dt>
          <dt>Weather Conditions <%= weather['main'] %> | <%= weather['description'].pluralize %></dt>
          <dd>
            <strong>Temp</strong> <%= @weather_response['main']['temp'].round %> ºF
            <strong>Min</strong> <%= @weather_response['main']['temp_min'].round %> ºF
            <strong>Max</strong> <%= @weather_response['main']['temp_max'].round %> ºF
          </dd>
        <% end %>
      </dl>
    </div>
  </div>
</div>